controllers:
    resource: ../../src/Controller/
    type: annotation
    prefix: /{_locale}
    requirements:
        _locale: '|de|en|es|fr|it|pl|pt'
    defaults:
        _locale: 'en'

kernel:
    resource: ../../src/Kernel.php
    type: annotation
